name: "Variable to File"
description: "Write the contents of a variable to a file"
inputs:
  contents:
    description: "Contents of the file to write"
    required: true
  file:
    description: "Location to write file contents"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        CONTENTS: ${{ inputs.contents }}
      run: |
        mkdir -p $(dirname "${{ inputs.file }}")
        echo "${CONTENTS}" > ${{ inputs.file }}
