name: "Test Container"
description: "Test Container using Buildah"
inputs:
  image:
    description: "Name of the image to build, without the tag."
    required: true
  target:
    description: "Build target (Default 'test')."
    required: true
    default: "test"
runs:
  using: "composite"
  steps:
    - name: Test
      shell: bash
      run: |
        buildah bud --squash --target=${{ inputs.target }} -t ${{ inputs.image }}:${GITHUB_SHA}-${{ inputs.target }} .
        buildah rmi ${{ inputs.image }}:${GITHUB_SHA}-${{ inputs.target }}
