name: "Cloud Connector Main CI"

on:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit
    with:
      tag: "main"
