name: "Cloud Connector Pull Request"

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit

  unit-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ${{ needs.build.outputs.image }}
    steps:
      - name: Test
        run: |
          cd /app
          pytest

  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ${{ needs.build.outputs.image }}
    steps:
      - name: Lint
        run: |
          cd /app
          black --check .
          isort --check .
          flake8 .
          mypy -p censys.cloud_connectors
