name: "Cloud Connector Pull Request"

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit
    with:
      test: "true"
      lint: "true"
