name: "Build Cloud Connector"

on:
  workflow_call:
    inputs:
      image:
        description: "Name of the image to build"
        required: false
        default: "gcr.io/censys-io/censys-cloud-connector"
        type: string
      test:
        description: "Whether to run tests"
        required: false
        default: "false"
        type: string
      lint:
        description: "Whether to run lint"
        required: false
        default: "false"
        type: string
      tag:
        description: "Additional tag to apply to the image"
        required: false
        default: ""
        type: string
      version:
        description: "Whether to tag the image with the version"
        required: false
        default: "false"
        type: string
    outputs:
      image:
        description: "Name of the built container image"
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}
    container:
      image: ghcr.io/censys/buildah:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        STORAGE_DRIVER: overlay
      options: --privileged
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        id: test
        if: ${{ github.event.inputs.test == 'true' }}
        uses: ./.github/actions/container-test-buildah
        with:
          image: ${{ github.event.inputs.image }}
          target: test
      
      - name: Lint
        id: lint
        if: ${{ github.event.inputs.lint == 'true' }}
        uses: ./.github/actions/container-test-buildah
        with:
          image: ${{ github.event.inputs.image }}
          target: lint

      - name: Build
        id: build
        uses: ./.github/actions/container-build-buildah
        with:
          credentials: ${{ secrets.DOCKER_AUTH_CONFIG }}
          image: ${{ github.event.inputs.image }}
          target: app
          tag: ${{ github.event.inputs.tag }}
          version: ${{ github.event.inputs.version }}

      - name: Tag Version
        id: tag-version
        if: ${{ github.event.inputs.version == 'true' }}
        uses: ./.github/actions/create-version-tag
